---
project:
  title: Mistral Meteo-Hub
  description: "."
  version: "0.6.7"
  rapydo: 0.6.7

variables:
  env:

    BACKEND_BUILD_MODE: backendcentos
    PYTHON_PATH: /usr/local/lib/python3.6/site-packages

    LOG_LEVEL: DEBUG

    ALCHEMY_USER: sqluser
    ALCHEMY_PASSWORD: chooseapasswordwisely
    ALCHEMY_API_DB: SQL_API
    ALCHEMY_ENGINE: postgresql
    ALCHEMY_DBS: SQL_API

    ACTIVATE_MONGODB: 1
    ACTIVATE_CELERY: 1
    ACTIVATE_CELERYUI: 1
    ACTIVATE_CELERY_BEAT: 1

    CELERY_BACKEND: MONGODB
    CELERY_BACKEND_HOST: mongo.dockerized.io
    CELERY_BACKEND_PORT: 27017

  backend:
    credentials:
      username: "user@nomail.org"
      password: "test"
      roles:
        user: normal_user
        internal: staff_user
        admin: admin_root
        default: normal_user
  frontend:
    framework: angular