---
project:
  title: Meteo-Hub
  description: "."
  version: "0.3.0"
  rapydo: 0.7.3

variables:
  env:

    # BACKEND_BUILD_MODE: backendcentos
    # PYTHON_PATH: /usr/local/lib/python3.6/dist-packages
    FRONTEND_FRAMEWORK: angular

    LOG_LEVEL: DEBUG

    ACTIVATE_ALCHEMY: 1
    ACTIVATE_POSTGRES: 1
    ALCHEMY_USER: sqluser
    # ALCHEMY_PASSWORD: chooseapasswordwisely
    ALCHEMY_API_DB: SQL_API
    ALCHEMY_ENGINE: postgresql
    ALCHEMY_DBS: 'SQL_API DBALLE'

    ACTIVATE_MONGODB: 1
    ACTIVATE_RABBIT: 1
    ACTIVATE_CELERY: 1
    ACTIVATE_CELERYUI: 1
    ACTIVATE_CELERY_BEAT: 1

    ACTIVATE_NIFI: 1

    CELERY_BACKEND: MONGODB

    LASTDAYS: 10

    RABBITMQ_ENABLE_MANAGEMENT_PLUGIN: 1
    # RABBITMQ_ENABLE_SHOVEL_PLUGIN: 1

    CORS_ALLOW_ALL_ORIGINS: 1

  backend:
    credentials:
      roles:
        user: normal_user
        internal: staff_user
        admin: admin_root
        default: normal_user

controller:
  commands:
    init:
      description: Init DB-All.e PostgreSQL database
      command: sh /scripts/init_dballe.sh
      service: backend
      user: developer
