# Customize this file to include compose configurations common to bluprints
version: '3'

services:
  backend:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    image: ${COMPOSE_PROJECT_NAME}/backend:${RAPYDO_VERSION}

    volumes:
      - ${VANILLA_DIR}/data/test:/data
      - ${VANILLA_DIR}/data/arkimet:/arkimet/datasets
      - ${VANILLA_DIR}/data/arkimet_2:/arkimet_2/datasets
      - ${VANILLA_DIR}/data/arkimet_conf:/arkimet/config
      - ${VANILLA_DIR}/data/cosmo-lami:/arkimet/cosmo-lami

  rabbit:
    ports:
      - 5672:5672
      - 15672:15672

  celeryui:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    image: ${COMPOSE_PROJECT_NAME}/backend:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/test:/data
      - ${VANILLA_DIR}/data/arkimet:/arkimet/datasets
      - ${VANILLA_DIR}/data/arkimet_2:/arkimet_2/datasets
      - ${VANILLA_DIR}/data/arkimet_conf:/arkimet/config

  celery:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    image: ${COMPOSE_PROJECT_NAME}/backend:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/test:/data
      - ${VANILLA_DIR}/data/arkimet:/arkimet/datasets
      - ${VANILLA_DIR}/data/arkimet_2:/arkimet_2/datasets
      - ${VANILLA_DIR}/data/arkimet_conf:/arkimet/config
      - ${VANILLA_DIR}/data/cosmo-lami:/arkimet/cosmo-lami

  # arkimet:
  #   restart: always
  #   build:
  #     context: ${PROJECT_DIR}/builds/arkimet
  #     # args:
  #     #   RAPYDO_VERSION: ${RAPYDO_VERSION}
  #     #   CURRENT_UID: ${CURRENT_UID}
  #   image: rapydo/arkimet:${RAPYDO_VERSION}
  #   # expose:
  #   #   - 8090
  #   ports:
  #     - 8090:8090
  #   networks:
  #     app_net:
  #       aliases:
  #         - arkimet
  #   volumes:
  #     - ${VANILLA_DIR}/data/arkimet:/datasets
  #   environment:
  #     ACTIVATE: 1

# volumes:
#   -

# networks:
#   -

