# Customize this file to include compose configurations common to bluprints
version: '3'

services:
  backend:
    # build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    # image: ${COMPOSE_PROJECT_NAME}/backend:${RAPYDO_VERSION}
    image: mdantonio/mistralbackend:0.7.1

    volumes:
      - ${VANILLA_DIR}/data/test:/data
      - ${VANILLA_DIR}/data/arkimet:/arkimet/datasets
      - ${VANILLA_DIR}/data/arkimet_conf:/arkimet/config
      - ${VANILLA_DIR}/data/cosmo-lami:/arkimet/cosmo-lami
      - ${VANILLA_DIR}/data/uploads:/uploads
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/scripts:/scripts

  postgres:
    image: postgres:11.5-alpine
    ports:
      - ${ALCHEMY_PORT}:${ALCHEMY_PORT}

  rabbit:
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}

#  nifi:
#    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/nifi
#    image: ${COMPOSE_PROJECT_NAME}/nifi:${RAPYDO_VERSION}
#    ports:
#      - 8070:8080
#    environment:
#      ACTIVATE: ${ACTIVATE_NIFI}

  celeryui:
    # build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    # image: ${COMPOSE_PROJECT_NAME}/backend:${RAPYDO_VERSION}
    image: mdantonio/mistralbackend:0.7.1
    volumes:
      - ${VANILLA_DIR}/data/test:/data
      - ${VANILLA_DIR}/data/arkimet:/arkimet/datasets
      - ${VANILLA_DIR}/data/arkimet_conf:/arkimet/config
      - ${VANILLA_DIR}/data/uploads:/uploads

  celery:
    # build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    # image: ${COMPOSE_PROJECT_NAME}/backend:${RAPYDO_VERSION}
    image: mdantonio/mistralbackend:0.7.1
    volumes:
      - ${VANILLA_DIR}/data/test:/data
      - ${VANILLA_DIR}/data/arkimet:/arkimet/datasets
      - ${VANILLA_DIR}/data/arkimet_conf:/arkimet/config
      - ${VANILLA_DIR}/data/cosmo-lami:/arkimet/cosmo-lami
      - ${VANILLA_DIR}/data/uploads:/uploads

  celery-beat:
    # build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    # image: ${COMPOSE_PROJECT_NAME}/backend:${RAPYDO_VERSION}
    image: mdantonio/mistralbackend:0.7.1

  # arkimet:
  #   restart: always
  #   build:
  #     context: ${PROJECT_DIR}/builds/arkimet
  #     # args:
  #     #   RAPYDO_VERSION: ${RAPYDO_VERSION}
  #     #   CURRENT_UID: ${CURRENT_UID}
  #   image: rapydo/arkimet:${RAPYDO_VERSION}
  #   # expose:
  #   #   - 8090
  #   ports:
  #     - 8090:8090
  #   networks:
  #     app_net:
  #       aliases:
  #         - arkimet
  #   volumes:
  #     - ${VANILLA_DIR}/data/arkimet:/datasets
  #   environment:
  #     ACTIVATE: 1

# volumes:
#   -

# networks:
#   -

