# variables:
#   DOCKER_DRIVER: overlay2
#   DOCKER_TLS_CERTDIR: ""
#   DOCKER_HOST: 'tcp://127.0.0.1:2375' 
  # DOCKER_COMPOSE_VERSION: 1.7.0

before_script:
  # - curl -fsSL https://get.docker.com/ | sh
  - docker -v
  - docker ps
  - sh scripts/create_projectrc.sh
  - rapydo install auto
  # - apt-get install python3-pip
  # - pip3 --version
  # - pip3 install rapydo-controller
  # - rapydo --version
  # - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  # - chmod +x docker-compose
  # - mv docker-compose /usr/local/bin
  # - pip install coveralls
  # - pip install python-coveralls

stages:
  - tests

script:
  stage: tests
  script:
    - rapydo init
    - rapydo remove
    - rapydo pull
    - rapydo update -i main --rebuild 
    - cp -r /arkimet/datasets/* data/arkimet/
    - rapydo start
    - export COMPOSE_INTERACTIVE_NO_CLI=1
    - rapydo shell --no-tty backend --command "restapi tests"
    - rapydo remove
