language: python
sudo: required
dist: bionic
python:
- 3.8
services:
- docker

env:
- VERSION=0.7.2

install:
- docker --version && docker-compose --version
- pip install --upgrade git+https://github.com/rapydo/do.git@$VERSION
- /bin/bash scripts/create_projectrc.sh
- rapydo init
- rapydo pull
- rapydo start

jobs:
  include:
  - stage: tests
    script: rapydo shell backend --command 'restapi tests --wait'
    env:
    - STAGE=backend
  - script: echo 1
    env:
    - STAGE=frontend