os: linux
dist: bionic
language: python
python:
- 3.8
services:
- docker

install:
- docker --version && docker-compose --version
- wget $DATASET_URL/arkimet.conf -O data/arkimet_conf/arkimet.conf
- wget $DATASET_URL/arkimet.zip
- unzip arkimet.zip -d data/
- ls data/
- mv data/arkimet/datasets/* data/arkimet/
- ls data/arkimet/
- pip install --upgrade git+https://github.com/rapydo/do.git@0.7.3
- /bin/bash scripts/create_projectrc.sh
- rapydo init
- rapydo pull
- rapydo dump
- rapydo start

jobs:
  include:
    - script: rapydo shell backend --command 'restapi tests --wait'
      env:
      - STAGE=BACKEND
    - script: docker-compose exec -d backend restapi start && sleep 20 && docker-compose up --exit-code-from frontend
      env:
      - STAGE=FRONTEND

notifications:
  email: true