language: python
sudo: required
dist: bionic
python:
- 3.8
services:
- docker

install:
- docker --version && docker-compose --version
- wget $DATASET_ZIP .
- unzip arkimet.zip -d data/
- ls data/
- ls data/arkimet/
- pip install --upgrade git+https://github.com/rapydo/do.git@0.7.2
- /bin/bash scripts/create_projectrc.sh
- rapydo init
- rapydo pull
- rapydo start


jobs:
  include:
  - stage: tests
    script: rapydo shell backend --command 'restapi tests --wait'
    env:
    - JOB=backend
    script: rapydo -s frontend logs && rapydo shell frontend --command 'npm run single-test'
    env:
    - JOB=frontend