os: linux
dist: bionic
language: python
python:
- 3.8
services:
- docker

install:
- pip install --upgrade git+https://github.com/rapydo/do.git@0.7.3
- TESTING=1 rapydo init

jobs:
  include:

    - script: wget $DATASET_URL/arkimet.conf -O data/arkimet_conf/arkimet.conf &&
              wget $DATASET_URL/arkimet.zip &&
              unzip arkimet.zip -d data/ &&
              mv data/arkimet/datasets/* data/arkimet/ &&
              rapydo pull &&
              rapydo start &&
              rapydo shell backend --command 'restapi tests --wait' &&
              docker cp mistral_backend_1:/code/coverage.xml coverage.xml && 
              bash <(curl -s https://codecov.io/bash)

      env:
      - STAGE=BACKEND

    - script: rapydo -s frontend pull &&
              rapydo dump &&
              docker-compose up --exit-code-from frontend frontend &&
              cp data/mistral/karma/lcov.info . &&
              bash <(curl -s https://codecov.io/bash)
      env:
      - STAGE=FRONTEND

notifications:
  email: true