language: python
sudo: required
dist: xenial
python:
- 3.7.1
services:
- docker
script:
  - docker -v
  - docker ps
  - sh scripts/create_projectrc.sh
  - pip3 install --upgrade --no-cache-dir rapydo-controller 
  - rapydo install auto
  - rapydo init
  - rapydo pull
  # - cp -r /arkimet/datasets/* data/arkimet/
  - rapydo start
  - rapydo shell backend --command 'restapi wait'
  - rapydo shell backend --command 'restapi forced-clean'
  - rapydo shell backend --command 'restapi init'
  - rapydo shell backend --command 'restapi tests'
  - rapydo remove

notifications:
  email: true
