language: python
sudo: required
dist: bionic
python:
- 3.8
services:
- docker
env:
- PROJECT=mistral

script:
- docker --version && docker-compose --version
- pip3 install rapydo-controller
- rapydo install auto
# - /bin/bash templates/create_testing_projectrc.sh 
- touch .projetrc
- rapydo init
- rapydo pull
- rapydo start
- rapydo shell backend --command 'restapi tests --wait'

