definitions:
  DataExtraction:
    required:
      - name
      - datasets
    properties:
      name:
        type: string
      reftime:
        $ref: "#/definitions/RefTime"
      datasets:
        description: Data belong to the datasets of the list.
        type: array
        uniqueItems: true
        minItems: 1
        items:
          description: Dataset name
          type: string
      filters:
        description: Apply different filtering criteria.
        $ref: "#/definitions/DataFilter"
      postprocessors:
        description: Apply one or more post-processing to the filtered data.
        type: array
        uniqueItems: true
        items:
          description: Post-processing request details
          type: object
      format:
        description: Output format
        type: string
        enum:
          - json
          - bufr
          - grib
  AVProcessor:
    description: Additional variables post-processing
    type: object
    properties:
      type:
        type: string
      variables:
        description: The list of requested additional variables to be calculated.
        type: array
        uniqueItems: true
        items:
          type: string
          enum:
            - B12194  # Air density
            - B13003  # Relative humidity
            - B11001  # Wind direction
            - B11002  # Wind speed
    required:
      - type
      - variables

  GIProcessor:
    description: Grid interpolation post processor to interpolate data on a new grid
    type: object
    properties:
      type:
        description: description of the postprocessor
        type: string
      boundings:
        description: boundings of the new grid
        type: object
        properties:
          x-min:
            type: number
          x-max:
            type: number
          y-min:
            type: number
          y-max:
            type: number
      points:
        description: number of point of the new grid
        type: object
        properties:
          nx:
            type: integer
          ny:
            type: integer
      trans-type:
        type: string
        enum:
          - inter
          - boxinter
      sub-type:
        type: string
        enum:
          - near
          - bilin
          - average
          - min
          - max
  GCProcessor:
    description: Grid cropping post processor
    type: object
    properties:
      type:
        description: description of the postprocessor
        type: string
      boundings:
        description: boundings of the cropped grid
        type: object
        properties:
          ilon:
            type: number
          ilat:
            type: number
          flon:
            type: number
          flat:
            type: number
      trans-type:
        type: string
        enum:
          - zoom
      sub_type:
        type: string
        enum:
          - coord
          - bbox
  SPIProcessor:
    description: Spare points interpolation postprocessor
    type: object
    properties:
      type:
        description: description of the postprocessor
        type: string
      file:
        description: file to define the spare points
        type: string
        format: binary
      format:
        description: format of the file
        type: string
        enum:
          - shp
        #ce ne sono altri??
      trans-type:
        type: string
        enum:
          - inter
          - polyinter
      sub-type:
        type: string
        enum:
          - near
          - bilin
          - average
          - min
          - max




#  GProcessor:
#    description: post-processor for geographical elaborations, interpolations or cropping
#    type: object
#    properties:
#      type:
#        type: string
#      input:
#        description: The list of input for the elaboration.
##        schema:
#        oneOf:
#          $ref: "#/definitions/GridInterpolation"
#          $ref: "#/definitions/GridCropping"
#          $ref: "#/definitions/SparePointInterpolation"
#        discriminator:
#          propertyName: method
#  GridInterpolation:
#    description: post processor to interpolate data on a new grid
#    type: object
#    properties:
#      method:
#        description: what kind of geographical interpolation
#        type: string
#      coordinates:
#        description: coordinate of the new grid
#        type: object
#        properties:
#         x-min:
#           type: number
#         x-max:
#           type: number
#         y-min:
#           type: number
#         y-max:
#           type: number
#      points:
#        description: number of point of the new grid
#        type: object
#        properties:
#         nx:
#           type: integer
#         ny:
#           type: integer

  RefTime:
    required:
      - from
      - to
    properties:
      from:
        type: string
        format: date-time
      to:
        type: string
        format: date-time
  DataFilter:
    properties:
      area:
        type: array
        items:
          type: object
      level:
        type: array
        items:
          type: object
      origin:
        type: array
        items:
          type: object
      proddef:
        type: array
        items:
          type: object
      product:
        type: array
        items:
          type: object
      quantity:
        type: array
        items:
          type: object
      run:
        type: array
        items:
          type: object
      task:
        type: array
        items:
          type: object
      timerange:
        type: array
        items:
          type: object
  Datasets:
    type: array
    items:
      $ref: "#/definitions/Dataset"
  Dataset:
    required:
      - name
      - fields
    properties:
      name:
        type: string
      fields:
        type: array
        items:
          type: string

#  Requests:
#    required:
#      - submission_date
#      - args
#      - user_name
#      - status
#      - fileoutput
#    properties:
#      submission_date:
#        type: string
#        format: dateTime
#      args:
#        type: object
#      user_name:
#        type: string
#      status:
#        type: string
#      fileoutput:
#        type: string

#  DataScheduling:
#    properties:
#      periode-settings:
#        description: Settings for the periodic request
#        type: object
#        properties:
#          every:
#            type: integer
#          period:
#            type: string
#            enum:
#              - days
#              - hours
#              - minutes
#              - seconds
#              - microseconds
#      crontab_settings:
#        description: Settings for the crontab request
#        type: object
#      minProperties: 1
#      maxProperties: 1
#      additionalProperties: none

  DataScheduling:
    required:
      - name
      - datasets
    properties:
      name:
        type: string
      reftime:
        $ref: "#/definitions/RefTime"
      datasets:
        description: Data belong to the datasets of the list.
        type: array
        uniqueItems: true
        minItems: 1
        items:
          description: Dataset name
          type: string
      filters:
        description: Apply different filtering criteria.
        $ref: "#/definitions/DataFilter"
      postprocessors:
        description: Apply one or more post-processing to the filtered data.
        type: array
        uniqueItems: true
        items:
          description: Post-processing request details
          type: object
      format:
        description: Output format
        type: string
        enum:
          - json
          - bufr
          - grib
      period-settings:
        description: Settings for the periodic request
        type: object
        $ref: "#/definitions/PeriodSettings"
      crontab-settings:
        description: Settings for the crontab request
        type: object
        $ref: "#/definitions/CrontabSettings"

  CrontabSettings:
    properties:
      minute:
        type: integer
        minimum: 0
        exclusiveMinimum: false
        maximum: 59
        exclusiveMaximum: false
      hour:
        type: integer
        minimum: 0
        exclusiveMinimum: false
        maximum: 23
        exclusiveMaximum: false
      day_of_week:
        type: integer
        minimum: 0
        exclusiveMinimum: false
        maximum: 7
        exclusiveMaximum: false
      day_of_month:
        type: integer
        minimum: 1
        exclusiveMinimum: false
        maximum: 31
        exclusiveMaximum: false
      month_of_year:
        type: integer
        minimum: 1
        exclusiveMinimum: false
        maximum: 12
        exclusiveMaximum: false
    minProperties: 1

  PeriodSettings:
      required:
        - every
        - period
      properties:
        every:
          type: integer
        period:
          type: string
          enum:
            - days
            - hours
            - minutes
            - seconds
            - microseconds

  Fileoutput:
    properties:
      fileoutput:
        type: string
        format: binary

  Requests:
    type: array
    items:
      $ref: "#/definitions/Request"
  Request:
    required:
      - id
      - name
      - args
      - status
      - submission_date
      - user_name
    properties:
      id:
        type: string
      name:
        type: string
      args:
        type: object
      status:
        type: string
        enum:
          - SUCCESS
          - ERROR
          - PENDING
      submission_date:
        type: string
        format: date
      end_date:
        type: string
        format: date
      task_id:
        type: string
      user_name:
        type: string
      fileoutput:
        type: string
      filesize:
        type: integer
        format: int64

  Summary:
    required:
      - items
    properties:
      items:
        type: object

#  Summary:
#    required:
#      - fields
#      - stats
#    properties:
#      fields:
#        type: array
#        items:
#          $ref: "#/definitions/Field"
#      stats:
#        $ref: "#/definitions/SummaryStats"
#  Field:
#    required:
#      - type
#      - values
#    properties:
#      type:
#        type: string
#      values:
#        type: array
#        items: {}
#  SummaryStats:
#    required:
#      - size
#      - count
#      - from
#      - to
#    properties:
#      size:
#        type: integer
#        minimum: 0
#      count:
#        type: integer
#        minimum: 0
#      from:
#        type: string
#        format: date-time
#      to:
#        type: string
#        format: date-time

#  Observation:
#    properties:
#      phenomenonTime:
#        type: string
#  Location:
#    properties:
#
#  Procedure:
#    name:
#      type: string
#    description:
#      type: string
#    type:
#      type: string
#
#  TimeRange:
#    pindicator:
#      type: string
#    period1:
#      type: string
#    period2:
#      type: string
  StorageUsage:
    required:
      - quota
      - used
    properties:
      quota:
        description: Current disk user quota (in bytes)
        type: integer
        format: int64
        minimum: 0
      used:
        description: Current disk usage (in bytes)
        type: integer
        format: int64
        minimum: 0

FormDataParameters:
  AdminUsers:
    - name: disk_quota
      in: formData
      type: number
      required: true
      description: Disk quota in bytes
      custom:
        label: Disk quota
